# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: java selenium ci

on:
  push:
    branches:
      - '**'
  pull_request:
      

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Set Up Maven
      run: |
          wget -q https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
          tar -xzf apache-maven-3.6.3-bin.tar.gz
          export PATH=$(pwd)/apache-maven-3.6.3/bin:$PATH

    - name: Set Up Chrome Browser
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: 'latest'

    - name: Check build environment
      run: |
        echo "Java version:"
        java -version

        echo "Maven version"
        mvn -version

        echo "Chrome version:"
        google-chrome --version

    - name: Execute test
      run: mvn clean test -Pheadless-chrome,qa,smoke-test

    - name: Archive test reports
      if: always()
      uses: action/upload-artifact@v3
      with:
         name: test-reports
         path: reports
